import type { Metadata } from "next";
import { Figtree, Manrope } from "next/font/google";
import "../globals.css"; // Perhatikan path naik satu level (../)
import LenisScrollProvider from "../LenisProvider"; // Sesuaikan path jika perlu
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Suspense } from "react";
import TopLoadingBar from "@/components/TopLoadingBar";
import GlobalAlert from "@/components/dashboard/GlobalAlert";
import QueryProvider from "@/providers/QueryProvider";
import Providers from "@/components/Providers";

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Shortlinkmu",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  // 👇 UBAH DI SINI: Tambahin Promise<...>
  params: Promise<{ locale: string }>;
}) {
  // 👇 UBAH DI SINI: Await params-nya dulu
  const { locale } = await params;

  // Validasi locale
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale} className="scroll-smooth" suppressHydrationWarning>
      {/* ... (Isi body sama aja) ... */}
      <body
        className={`${figtree.variable} ${manrope.variable} font-figtree antialiased`}
      >
        <Suspense fallback={<div />}>
          <TopLoadingBar />
        </Suspense>
        <LenisScrollProvider>
          <NextIntlClientProvider messages={messages}>
            <Providers>
              <QueryProvider>
                <GlobalAlert />
                {children}
              </QueryProvider>
            </Providers>
          </NextIntlClientProvider>
        </LenisScrollProvider>
      </body>
    </html>
  );
}
